sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t sungjin0757/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sungjin0757/react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northest-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-810012734123"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY